src/Condensate.Mvc/Models/ErrorViewModel.cs
using System;

namespace Condensate.Mvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Condensate.Mvc/Controllers/GameNewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Condensate.SteamApi;
using Condensate.SteamApi.ResponseModels;
using Microsoft.AspNetCore.Mvc;

namespace Condensate.Mvc.Controllers
{
    public class GameNewsController : Controller
    {
        private SteamApiClient _steamApi;

        public GameNewsController()
        {
            _steamApi = new SteamApiClient();
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult InputAppid(int appid)
        {
            var gameNews = _steamApi.GetGameNews(appid);
            if (gameNews.appnews != null)
            {
                foreach (var newsItem in gameNews.appnews.newsitems)
                {
                    newsItem.contents = newsItem.contents.Replace("{STEAM_CLAN_IMAGE}", "https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/clans/");
                    newsItem.contents = newsItem.contents.Replace("[img]", "<img src=\"");
                    newsItem.contents = newsItem.contents.Replace("[/img]", "\" alt/ width=\"668\" height=\"376\">");
                    newsItem.contents = newsItem.contents.Replace("[list]", "<ul>");
                    newsItem.contents = newsItem.contents.Replace("[/list]", "</ul>");
                    newsItem.contents = newsItem.contents.Replace("[olist]", "<ol>");
                    newsItem.contents = newsItem.contents.Replace("[/olist]", "</ol>");
                    newsItem.contents = newsItem.contents.Replace("[*]", "<li>");
                    newsItem.contents = newsItem.contents.Replace("[/*]", "</li>");
                    newsItem.contents = newsItem.contents.Replace("[b]", "<b>");
                    newsItem.contents = newsItem.contents.Replace("[/b]", "</b>");
                    newsItem.contents = newsItem.contents.Replace("[i]", "<i>");
                    newsItem.contents = newsItem.contents.Replace("[/i]", "</i>");
                    newsItem.contents = newsItem.contents.Replace("\n", "<br />");
                    newsItem.contents = newsItem.contents.Replace("[h3]", "<h3>");
                    newsItem.contents = newsItem.contents.Replace("[/h3]", "</h3>");
                    newsItem.contents = newsItem.contents.Replace("[h1]", "<h1>");
                    newsItem.contents = newsItem.contents.Replace("[/h1]", "</h1>");
                }
                return View(gameNews);
            }
            else
            {
                return View("Index");
            }
        }
    }
}

src/Condensate.Mvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Condensate.Mvc.Models;

namespace Condensate.Mvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Condensate.Mvc/Controllers/NewsFeedController.cs
using Condensate.SteamApi;
using Condensate.SteamApi.ResponseModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Condensate.Mvc.Controllers
{
    public class NewsFeedController : Controller
    {
        private SteamApiClient _steamApi;

        public NewsFeedController()
        {
            _steamApi = new SteamApiClient();
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> InputCommunityIdForNewsFeed(string communityid, int count)
        {
            var myGames = _steamApi.GetCommunityProfileGames(communityid);
            myGames.Games.GameList = myGames.Games.GameList.OrderBy(x => int.Parse(x.AppID)).ToList();
            var newsFeed = new List<GameNewsItem>();


            //thread this to make it go faster
            var games = new List<GameNewsResponse>();
            var batchSize = 100;
            int numberOfBatches = (int)Math.Ceiling((double)myGames.Games.GameList.Count() / batchSize);

            for (int i = 0; i < numberOfBatches; i++)
            {
                var currentIds = myGames.Games.GameList.Skip(i * batchSize).Take(batchSize);
                var tasks = currentIds.Select(game => _steamApi.GetGameNewsAsync(int.Parse(game.AppID)));
                games.AddRange(await Task.WhenAll(tasks));
            }

            foreach(var gameNewsResponse in games)
            {
                newsFeed.AddRange(gameNewsResponse.appnews.newsitems);
            }

            foreach (var newsFeedItem in newsFeed)
            {
                newsFeedItem.gameProfile = myGames.Games.GameList.Where(x => x.AppID == newsFeedItem.appid.ToString()).FirstOrDefault();
                if(newsFeedItem.gameProfile == null)
                {
                    newsFeedItem.gameProfile = new Game
                    {
                        Name = ""
                    };
                }
                else if(newsFeedItem.gameProfile.Name == null)
                {
                    newsFeedItem.gameProfile.Name = "";
                }
            }
            newsFeed.RemoveAll(x => x.gameProfile.Name == "");

            newsFeed = newsFeed.OrderByDescending(x => x.date).ToList();

            foreach (var newsItem in newsFeed)
            {
                newsItem.contents = newsItem.contents.Replace("{STEAM_CLAN_IMAGE}", "https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/clans/");
                newsItem.contents = newsItem.contents.Replace("[img]", "<img class=\"gameNewsContentImage\" src=\"");
                newsItem.contents = newsItem.contents.Replace("[/img]", "\" alt/ width=\"668\" height=\"376\">");
                newsItem.contents = newsItem.contents.Replace("[list]", "<ul>");
                newsItem.contents = newsItem.contents.Replace("[/list]", "</ul>");
                newsItem.contents = newsItem.contents.Replace("[olist]", "<ol>");
                newsItem.contents = newsItem.contents.Replace("[/olist]", "</ol>");
                newsItem.contents = newsItem.contents.Replace("[*]", "<li>");
                newsItem.contents = newsItem.contents.Replace("[/*]", "</li>");
                newsItem.contents = newsItem.contents.Replace("[b]", "<b>");
                newsItem.contents = newsItem.contents.Replace("[/b]", "</b>");
                newsItem.contents = newsItem.contents.Replace("[i]", "<i>");
                newsItem.contents = newsItem.contents.Replace("[/i]", "</i>");
                newsItem.contents = newsItem.contents.Replace("[u]", "<u>");
                newsItem.contents = newsItem.contents.Replace("[/u]", "</u>");
                newsItem.contents = newsItem.contents.Replace("\n", "<br />");
                newsItem.contents = newsItem.contents.Replace("[h1]", "<h1>");
                newsItem.contents = newsItem.contents.Replace("[/h1]", "</h1>");
                newsItem.contents = newsItem.contents.Replace("[h2]", "<h2>");
                newsItem.contents = newsItem.contents.Replace("[/h2]", "</h2>");
                newsItem.contents = newsItem.contents.Replace("[h3]", "<h3>");
                newsItem.contents = newsItem.contents.Replace("[/h3]", "</h3>");
                


                newsItem.ReplaceUrlInContents();
            }

            return View(newsFeed);
        }
    }
}

src/Condensate.Mvc/Views/GameNews/Index.cshtml
Enter a steam appid below to view the news for that game

@using (Html.BeginForm("InputAppid", "GameNews", FormMethod.Get))
{
    <input type="number" name="appid" id="appid" />

    <input type="submit" value="InputAppid" />
}

src/Condensate.Mvc/Views/GameNews/InputAppid.cshtml
@model Condensate.SteamApi.ResponseModels.GameNewsResponse

@using (Html.BeginForm("InputAppid", "GameNews", FormMethod.Get))
{
    <input type="number" name="appid" id="appid" />

    <input type="submit" value="InputAppid" />
}

<h1>@Model.appnews.appid</h1>

@foreach (var gameNewsItem in Model.appnews.newsitems)
{
    <div>
        <h3>@gameNewsItem.title</h3>
        <br />
        @Html.Raw(gameNewsItem.contents)
        <hr style="color:#919090; background-color:#919090; height:1px; border:none;" />
        <br />
    </div>
}

src/Condensate.Mvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/Condensate.Mvc/Views/MyGames/Index.cshtml
@using (Html.BeginForm("InputCommunityId", "MyGames", FormMethod.Get))
{
    <input type="text" name="communityid" id="communityid" />

    <input type="submit" value="Show my games" />
}

src/Condensate.Mvc/Views/MyGames/InputCommunityId.cshtml
@model Condensate.SteamApi.ResponseModels.CommunityProfileGamesResponse

@using (Html.BeginForm("InputCommunityId", "MyGames", FormMethod.Get))
{
    <input type="text" name="communityid" id="communityid" />

    <input type="submit" value="Show my games" />
}
<div>
    <h1>Game List for @Model.SteamID</h1>
    <hr style="color:#919090; background-color:#919090; height:1px; border:none;" />
    <br />
</div>
<div>

    @foreach (var game in Model.Games.GameList)
    {
        <div>
            <img src="@game.Logo">
            <h3>@game.Name</h3>
            <ul>
                <li>@game.HoursOnRecord hours of play on record.</li>
                <li><a asp-controller="GameNews" asp-action="InputAppid" asp-route-appid="@game.AppID">GameNews</a></li>
            </ul>

            <hr style="color:#919090; background-color:#919090; height:1px; border:none;" />

            <br />
        </div>
    }
</div>

src/Condensate.Mvc/Views/NewsFeed/Index.cshtml
@using (Html.BeginForm("InputCommunityIdForNewsFeed", "NewsFeed", FormMethod.Get))
{
    <p>SteamId:</p><input type="text" name="communityid" id="communityid" />

    <p>Number of NewsItemsPerGame:</p><input type="number" name="count" id="count" />

    <input type="submit" value="Show my news feed" />
}

src/Condensate.Mvc/Views/NewsFeed/InputCommunityIdForNewsFeed.cshtml
@model List<Condensate.SteamApi.ResponseModels.GameNewsItem>


@foreach (var gameNewsItem in Model.Take(100))
{
<div class="gameNewsItem">
    @if (gameNewsItem.gameProfile != null)
    {
        if (gameNewsItem.gameProfile.Logo != null)
        {
            <img class="gameProfileLogo" src="@gameNewsItem.gameProfile.Logo">
        }
    }
    <h6 class="gameProfileName">@gameNewsItem.gameProfile.Name</h6>
    <h1 class="gameNewsHeader">@gameNewsItem.title</h1>
    <div class="gameNewsDatetime">
        @gameNewsItem.dateTime
    </div>
    <div class="gameNewsContents">
        @Html.Raw(gameNewsItem.contents)
    </div>
</div>
}

src/Condensate.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Condensate MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Condensate MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MyGames" asp-action="Index">MyGames</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="GameNews" asp-action="Index">GameNews</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NewsFeed" asp-action="Index">NewsFeed</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Condensate MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>